version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u admin -p 1234 --quiet | grep 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-db: